from django.contrib import admin
from django.urls import path
from home import views
urlpatterns = [
     path("",views.index,name= 'home'),
     path("about",views.about,name= 'about'), 
     path("services",views.services,name= 'services'),
     path("contact",views.contact,name= 'contact'),
     path("prelogin",views.prelogin,name= 'prelogin'),
     path("adminlogin/",views.adminlogin,name= 'adminlogin'),
     path("dispatchlogin/",views.dispatchlogin,name= 'dispatchlogin'),
     path("mislogin/",views.mislogin,name= 'mislogin'),
     path("courierlogin/",views.courierlogin,name= 'courierlogin'),
     path("bookinglogin/",views.bookinglogin,name= 'bookinglogin'),
     path("registeradmin/" , views.registeradmin , name='registeradmin'),
     path("registerbooking/" , views.registerbooking , name='registerbooking'),
     path("registerdispatch/" , views.registerdispatch , name='registerdispatch'),
     path("registermis/" , views.registermis , name='registermis'),
     path("registernewuser/" , views.registernewuser , name='registernewuser'),
     path("registernewcompany/" , views.registernewcompany , name='registernewcompany'),
     path("registercourier/" , views.registercourier , name='registercourier'),
     path("postregisternewcompany/" , views.postregisternewcompany , name='postregisternewcompany'),
    
    
     path("postregisteradmin/" , views.postregisteradmin , name='postregisteradmin'),
     path("postregisterbooking/" , views.postregisterbooking , name='postregisterbooking'),
     path("postregistermis/" , views.postregistermis , name='postregistermis'),
     path("postregisterdispatch/" , views.postregisterdispatch , name='postregisterdispatch'),
     path("login/" , views.login ,name='login' ),
     path("lh1/" , views.lh1 ,name='lh1' ),
     path("lh2/" , views.lh2 ,name='lh2' ),
     path("lh3/" , views.lh3 ,name='lh3' ),
     path("lh4/" , views.lh4 ,name='lh4' ),
     path("postloginadmin/" , views.postloginadmin ,name='postloginadmin' ),
     path("postloginbooking/" , views.postloginbooking ,name='postloginbooking' ),
     path("postloginmis/" , views.postloginmis ,name='postloginmis' ),
     path("postlogindispatch/" , views.postlogindispatch ,name='postlogindispatch' ),
     path("forget/" , views.forget ,name='forget' ),
     path("postreset/" , views.postreset ,name='postreset' ),
     path("usertable/" , views.usertable ,name='usertable' ),
     path("checkuserupdate/" , views.checkuserupdate ,name='checkuserupdate' ),
     path("postcheckuserupdate/" , views.postcheckuserupdate ,name='postcheckuserupdate' ),
     path("postdeleteuser/" , views.postdeleteuser ,name='postuserdelete' ),
     path("deleteuser/" , views.deleteuser ,name='deleteuser' ),
   
     path("courierorder/" , views.courierorder ,name='courierorder' ),
     path("confirmedcourierorder/" , views.confirmedcourierorder,name='confirmedcourierorder' ),
   
     path("postbookingorder/" , views.postbookingorder ,name='postbookingorder' ),
     path("postconfirmbookingorder/" , views.postconfirmbookingorder ,name='postconfirmbookingorder' ),
     path("postmis/" , views.postmis ,name='postmis' ),
     path("producttablestatus/" , views.producttablestatus ,name='producttablestatus' ),
     path("producttable/" , views.producttable ,name='producttable' ),
     path("bookingorder1/" , views.bookingorder1 ,name='bookingorder1' ),
     path("postuserupdate/" , views.postuserupdate ,name='postuserupdate' ),
     path("postbookingorder1/" , views.postbookingorder1 ,name='postbookingorder1' ) ,
     path("postdispatchuser/" , views.postdispatchuser ,name='postdispatchuser' ),
     path("dispatchuser/" , views.dispatchuser ,name='dispatchuser' ),
     path("dispatchuser1/" , views.dispatchuser1 ,name='dispatchuser1' ),
     path("confirmdispatch/" , views.confirmdispatch ,name='confirmdispatch' ),
     path("postconfirmdispatch/" , views.postconfirmdispatch ,name='postconfirmdispatch' ),
     path("dispatchpanel/" , views.dispatchpanel ,name='dispatchpanel' ),
     path("dispatchconfirm/" , views.dispatchconfirm ,name='dispatchconfirm' ),
     path("viewdispatchorders/" , views.viewdispatchorders ,name='viewdispatchorders' ),
     path("postviewdispatchuser/" ,views.postviewdispatchuser , name="postviewdispatchuser" ),
     path("lh3render/" ,views.lh3render , name="lh3render" ),
     path("ordersconfirmedbydispatch/" ,views.ordersconfirmedbydispatch , name="ordersconfirmedbydispatch" )

     
]